steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_GCR_REGISTRY/$_GCP_ID/$_GCR_PATH:$SHORT_SHA', '.']
    
  # Step 2: Push Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_GCR_REGISTRY/$_GCP_ID/$_GCR_PATH:$SHORT_SHA']
options:
  logging: CLOUD_LOGGING_ONLY